version: '3.8'

services:
  db:
    image: postgres
    container_name: db_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - fastapi_network

  redis:
    image: redis
    container_name: fastapi_redis
    restart: always
    networks:
      - fastapi_network

  celery:
    build: .
    container_name: fastapi_celery
    command: celery -A app.celery.tasks worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - fastapi_network
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  flower:
    build: .
    container_name: fastapi_flower
    command: celery -A app.celery.tasks flower
    depends_on:
      - celery
    networks:
      - fastapi_network
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

volumes:
  pg_data:

networks:
  fastapi_network:
    driver: bridge